name: Helpdesk API - CI Pipeline

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install API Dependencies
        working-directory: ./helpdesk-api
        run: npm install

      - name: Install Cypress Dependencies
        working-directory: ./helpdesk-testes
        run: npm install

      - name: Install Root Dependencies
        run: npm install

      - name: Run API and Tests
        run: npm test
